services:
  frontend:
    build: ./frontend
    container_name: acme-frontend
    restart: always
    ports:
      - "80:3000"
    networks:
      - acme-net

networks:
  acme-net:
    driver: bridge